framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: 'news_broker'
                
            sync: 'sync://'

        routing:
            'App\Message\NewsSourcesMessage': async
