version: '3'

services:
  database:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: app
        MYSQL_USER: app
        MYSQL_PASSWORD: 1234
      ports:
        - '4306:3306'
      volumes:
        - ./mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database

  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: 1234
    ports:
      - "15672:15672"
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
  rabbitmq-data:
###< doctrine/doctrine-bundle ###
